= Kolophon
:icons:         font
:imagesdir:     ../../images
:imagesoutdir:  ../../images
:linkattrs:
:toc:           macro
:toc-title:     Inhalt

ntpstats-ng - Vom ASCII-Text zum "`GitBook`"

IMPORTANT: Dieses Kapitel wird editiert und ist noch nicht abgeschlossen.

toc::[]

== AsciiDoctor

Quellen sind xref:Appendix-Bookmarks.adoc#bookmark_asciidoc_writers_guide[AsciiDoc Writer’s Guide] und xref:Appendix-Bookmarks.adoc#bookmark_asciidoctor_user_manual[Asciidoctor User Manual].

=== Formatierungen

==== Überschriften

.Syntax
[source%nowrap, asciidoc]
----
= Document Title (Level 0)
== Level 1
=== Level 2
==== Level 3
===== Level 4
----

==== Absätze und Zeilenumbruch

.Syntax
[source%nowrap, asciidoc]
----
Das ist der erste Satz vom ersten Absatz.
Das ist der zweite Satz vom ersten Absatz.

Das ist der erste Satz vom zweiten Absatz. +
Das ist der zweite Satz vom zweite Absatz.
Das ist der dritte Satz vom zweiten Absatz.

Das ist der erste Satz vom dritten Absatz.
----

====
Das ist der erste Satz vom ersten Absatz.
Das ist der zweite Satz vom ersten Absatz.

Das ist der erste Satz vom zweiten Absatz. +
Das ist der zweite Satz vom zweite Absatz.
Das ist der dritte Satz vom zweiten Absatz.

Das ist der erste Satz von dritten Absatz.
====

==== Anführungszeichen

.Syntax
[source%nowrap, asciidoc]
----
Text in '`einfachen Anführungszeichen`'.

Text in "`doppelten Anführungszeichen`".
----

====
Text in '`einfachen Anführungszeichen`'.

Text in "`doppelten Anführungszeichen`".
====

==== Fußnote

.Syntax
[source%nowrap, asciidoc]
----
Ein Satz mit Link in der Fußnote.footnote:[link:Colophon.adoc#_fußnote[Colophon - Fußnote]]
----

====
Ein Satz mit Link in der Fußnote.footnote:[link:Colophon.adoc#_fußnote[Colophon - Fußnote]]
====

==== Admonitions

.Syntax
[source%nowrap, asciidoc]
----
NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING
----

====
NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING
====

== Lokal

.asciidoctor-1.5.5
[source%nowrap, sh]
----
asciidoctor -r asciidoctor-diagram -D doc/de/html doc/de/doc/*.adoc
asciidoctor -r asciidoctor-diagram -D doc/de/html/html doc/de/doc/*/*.adoc
----

== GitHub

TODO

== GitBook

TODO

'''

link:README.adoc[ntpstats-ng] (C) MMXV-MMXVII WOLfgang Schricker

// End of ntpstats-ng/doc/de/doc/Colophon.adoc
