= Logstash
:icons:         font
:linkattrs:
:toc:           macro
:toc-title:     Inhalt

ELG Stack = link:Elasticsearch.adoc[Elasticsearch], Logstash und link:Grafana.adoc[Grafana]

toc::[]

== Erste Schritte

Um die Verwendung von Logstash zu verstehen, soll als erstes Beispiel die Log-Datei `/var/log/ntp/ntp.log` überwacht und als Datei im JSON-Format abgespeichert werden.

== Konfiguration

=== ntpd

----
mkdir /var/log/ntp
chown ntp:ntp /var/log/ntp
----

.Gentoo, ntp-4.2.8p9
----
# /etc/conf.d/ntpd

NTPD_OPTS="-u ntp:ntp -l /var/log/ntp/ntp.log"
----

.CentOS 7, ntp-4.2.6p5
----
# /etc/sysconfig/ntpd
#
# see also /usr/lib/systemd/system/ntpd.service

OPTIONS="-g -l /var/log/ntp/ntp.log"
----

=== logstash

Die Logstash-Konfiguration teilt sich in die Abschnitte `input`, `filter` und
`output`.

Als `input`-Typ wird `ntplog` festgelegt.

Der Zeitstempel-Anteil des `output`-Dateinamens wird im xref:A-Bookmarks.adoc#bookmark_joda_time[Joda-Time-Format] angegeben.

.logstash-5.1.2
----
# /etc/logstash/conf.d/ntpstats-ng.conf

input {
    file {
        path => [ "/var/log/ntp/ntp.log" ]
        type => "ntplog"
    }
}

filter {}

output {
    if [type] == "ntplog" {
        file {
            path => "/tmp/ntpstats-ng-%{+YYYYMMdd}.json"
        }
    }
}
----

== Es funktioniert!

Die Dienste `ntpd` und `logstash` werden mit der oben beschriebene Konfiguration gestartet.

.Gentoo, openrc
----
/etc/init.d/logstash start
/etc/init.d/ntpd start
----

.CentOS 7, syslogd
----
systemctl start logstash.service
systemctl start ntpd.service
----



TIP: Wird fortgesetzt...

'''

link:README.adoc[ntpstats-ng] (C) 2015-2017 WOLfgang Schricker

// End of ntpstats-ng/doc/de/doc/Logstash.adoc
